Week4/ConcertNetwork/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "/", to: "concerts#index"
resources :concerts do
    resources :comments
end
end

Week4/ConcertNetwork/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :concert
  validates :author, { presence: true }
  validates :comment, { presence: true }

end

Week4/ConcertNetwork/app/models/concert.rb
class Concert < ApplicationRecord
  has_many :comments
  
  validates :artist, { presence: true }
  validates :venue, { presence: true }
  validates :city, { presence: true }
  validates :date, { presence: true }
  validates :price, { numericality: true }
end

Week4/ConcertNetwork/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @myconcert = Concert.find(params[:concert_id])
    @mycomment = @myconcert.comments
  end

  	def create
  		@myconcert = Concert.find(params[:concert_id])
  		@mycomment = @myconcert.comments.new(
  			author: params[:comment][:author],
  			date: params[:comment][:date],
  			comment: params[:comment][:comment])

  		if @mycomment.save
  			redirect_to(concert_path(@myconcert))
      else
        render :new
  		end
  	end
  end

Week4/ConcertNetwork/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
      @concertstoday = Concert.where(date: DateTime.now.to_date..Date.tomorrow)
      @concertsthismonth = Concert.where(date: Date.tomorrow..Date.today.end_of_month)
      render :index
  end
  def show
    @concert = Concert.find(params[:id])
    @mycomment = @concert.comments.new
    render :show
  end

  def new
  @the_concert = Concert.new
  render :new
end

def create
  @the_concert = Concert.new(
    artist: params[:concert][:artist],
    venue: params[:concert][:venue],
    city: params[:concert][:city],
    date: params[:concert][:date],
    price: params[:concert][:price],
    description: params[:concert][:description])

    @the_concert.save

  redirect_to("/concerts")
  end
end

Week4/ConcertNetwork/app/helpers/comments_helper.rb
module CommentsHelper
end

Week4/ConcertNetwork/app/helpers/concerts_helper.rb
module ConcertsHelper
end

Week4/ConcertNetwork/app/views/partials/_footer.html.erb
  <footer class="page-footer">
               <div class="container">
                 <div class="row">
                   <div class="col l6 s12">
                     <h5 class="white-text"> Nicaragua's Music Scene </h5>
                     <p class="grey-text text-lighten-4"> León | Granada | Managua | San Juan del Sur |</p>
                   </div>
                   <div class="col l4 offset-l2 s12 right-align">
                     <h5 class="white-text">Join us!</h5>
                     <ul>
                       <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
                       <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
                       <li><a class="grey-text text-lighten-3" href="#!">Instagram</a></li>
                       <li><a class="grey-text text-lighten-3" href="#!">YouTube</a></li>
                     </ul>
                   </div>
                 </div>
               </div>
             </footer>

Week4/ConcertNetwork/app/views/partials/_header.html.erb
<div class="navbar-fixed">
    <nav>
      <div class="container">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Concertful</a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "Home", concerts_path %></li>
          <li><%= link_to "Add a new concert", new_concert_path %></li>
        </ul>
      </div>
    </div>
    </nav>
  </div>