Week4/AuctionSite/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get '/', to: 'landing_pages#home', as: 'home'
get 'users/:id', to: 'users#show', as: 'user'
end

Week4/AuctionSite/app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :product
end

Week4/AuctionSite/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bids
end

Week4/AuctionSite/app/models/user.rb
class User < ApplicationRecord
  has_many :products
  
  validates :name, { presence: true }
  validates :email, { presence: true }
end

Week4/AuctionSite/app/controllers/bid_controller.rb
class BidController < ApplicationController
end

Week4/AuctionSite/app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def home
    render :home
  end
end

Week4/AuctionSite/app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

Week4/AuctionSite/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  @user = User.find params[:id]
end
end

Week4/AuctionSite/app/helpers/bid_helper.rb
module BidHelper
end

Week4/AuctionSite/app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

Week4/AuctionSite/app/helpers/products_helper.rb
module ProductsHelper
end

Week4/AuctionSite/app/views/users/show.html.erb
<header>
<h1> Eby <h1>
<h4> - Simplify - </h4>
<h2> Top brands. Free shipping. More deals. </h2>
<h3> Start the season with big savings </h3>
</header>

<h2> Users </h2>
<%= link_to '/', home_path %>
<ul style="list-style: none;">
  <% @user.each do |a_user| %>
    <li> Name: <%= a_user.name %> </li>
    <li> Mobile: <%= a_user.email%> </li>
  <% end %>
</ul>